# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from dotenv import load_dotenv

load_dotenv()

class Settings:
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_REGION = os.getenv("AWS_REGION", "us-east-1")
    DYNAMODB_TABLE_BOOKS = "reading_tracker_books"
    DYNAMODB_TABLE_READING_LOGS = "reading_tracker_logs"
    DYNAMODB_TABLE_GOALS = "reading_tracker_goals"

settings = Settings()
