// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from 'react';
import { X } from 'lucide-react';
import { booksAPI } from '../services/api';

const AddBookModal = ({ onClose, onBookAdded, initialStatus = 'to-read' }) => {
  const [formData, setFormData] = useState({
    title: '',
    author: '',
    total_pages: '',
    status: initialStatus,
    cover_url: ''
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const bookData = {
        ...formData,
        total_pages: parseInt(formData.total_pages),
        current_page: 0,
        created_at: new Date().toISOString()
      };
      
      await booksAPI.create(bookData);
      onBookAdded();
      onClose();
    } catch (error) {
      console.error('Error adding book:', error);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h2>Add New Book</h2>
          <button onClick={onClose} className="btn-secondary" style={{ padding: '0.5rem' }}>
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Title *</label>
            <input
              type="text"
              required
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            />
          </div>

          <div className="form-group">
            <label>Author *</label>
            <input
              type="text"
              required
              value={formData.author}
              onChange={(e) => setFormData({ ...formData, author: e.target.value })}
            />
          </div>

          <div className="form-group">
            <label>Total Pages *</label>
            <input
              type="number"
              required
              value={formData.total_pages}
              onChange={(e) => setFormData({ ...formData, total_pages: e.target.value })}
            />
          </div>

          <div className="form-group">
            <label>Status</label>
            <select
              value={formData.status}
              onChange={(e) => setFormData({ ...formData, status: e.target.value })}
            >
              <option value="to-read">To Be Read</option>
              <option value="reading">Currently Reading</option>
              <option value="completed">Completed</option>
            </select>
          </div>

          <div className="form-group">
            <label>Cover URL (optional)</label>
            <input
              type="url"
              value={formData.cover_url}
              onChange={(e) => setFormData({ ...formData, cover_url: e.target.value })}
            />
          </div>

          <div className="form-actions">
            <button type="button" onClick={onClose} className="btn btn-secondary">
              Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              Add Book
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddBookModal;
