# Code Generated by Sidekick is for learning and experimentation purposes only.
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from .models.book import Book, ReadingLog, Goal
from .services.dynamodb_service import db_service
from typing import List
from datetime import datetime, timedelta
import sys
import os

# Add parent directory to path for config import
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

app = FastAPI(title="Reading Tracker API")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # Vite default port
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Books endpoints
@app.post("/api/books", response_model=Book)
async def create_book(book: Book):
    book_dict = book.dict()
    created_book = db_service.create_book(book_dict)
    return created_book

@app.get("/api/books", response_model=List[Book])
async def get_books(status: str = None):
    if status:
        books = db_service.get_books_by_status(status)
    else:
        books = db_service.get_all_books()
    return books

@app.put("/api/books/{book_id}")
async def update_book(book_id: str, updates: dict):
    db_service.update_book(book_id, updates)
    return {"message": "Book updated successfully"}

@app.delete("/api/books/{book_id}")
async def delete_book(book_id: str):
    db_service.delete_book(book_id)
    return {"message": "Book deleted successfully"}

# Reading logs endpoints
@app.post("/api/reading-logs", response_model=ReadingLog)
async def create_reading_log(log: ReadingLog):
    log_dict = log.dict()
    created_log = db_service.create_reading_log(log_dict)
    
    # Update book's current page
    logs = db_service.get_logs_by_book(log.book_id)
    total_pages_read = sum(l.get('pages_read', 0) for l in logs)
    db_service.update_book(log.book_id, {'current_page': total_pages_read})
    
    return created_log

@app.get("/api/reading-logs/book/{book_id}", response_model=List[ReadingLog])
async def get_logs_by_book(book_id: str):
    logs = db_service.get_logs_by_book(book_id)
    return logs

@app.get("/api/reading-logs/stats")
async def get_reading_stats():
    today = datetime.now().date()
    
    # Daily stats
    daily_logs = db_service.get_logs_by_date_range(
        today.isoformat(), 
        today.isoformat()
    )
    daily_pages = sum(log.get('pages_read', 0) for log in daily_logs)
    
    # Weekly stats
    week_start = (today - timedelta(days=today.weekday())).isoformat()
    weekly_logs = db_service.get_logs_by_date_range(week_start, today.isoformat())
    weekly_pages = sum(log.get('pages_read', 0) for log in weekly_logs)
    
    # Monthly stats
    month_start = today.replace(day=1).isoformat()
    monthly_logs = db_service.get_logs_by_date_range(month_start, today.isoformat())
    monthly_pages = sum(log.get('pages_read', 0) for log in monthly_logs)
    
    # Yearly stats
    year_start = today.replace(month=1, day=1).isoformat()
    yearly_logs = db_service.get_logs_by_date_range(year_start, today.isoformat())
    yearly_pages = sum(log.get('pages_read', 0) for log in yearly_logs)
    
    completed_books = len(db_service.get_books_by_status('completed'))
    
    return {
        "daily": {"pages": daily_pages},
        "weekly": {"pages": weekly_pages},
        "monthly": {"pages": monthly_pages},
        "yearly": {"pages": yearly_pages, "books": completed_books}
    }

# Goals endpoints
@app.post("/api/goals", response_model=Goal)
async def create_goal(goal: Goal):
    goal_dict = goal.dict()
    created_goal = db_service.create_goal(goal_dict)
    return created_goal

@app.get("/api/goals", response_model=List[Goal])
async def get_goals():
    goals = db_service.get_all_goals()
    return goals

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
